--\encoding SJIS
--\encoding UTF8
INSERT INTO CUSTOMER (
  CUSTOMER_CODE,
  CUSTOMER_NAME,
  CUSTOMER_KANA,
  CUSTOMER_PASS,
  CUSTOMER_BIRTH,
  CUSTOMER_JOB,
  CUSTOMER_TEL,
  CUSTOMER_POST,
  CUSTOMER_ADD
 ) VALUES (
   '00000001',
   '渡辺利典',
   'ワタナベトシノリ',
   'password',
   '1986-08-18',
   '会社員',
   '080-5900-6966',
   '164-0012',
   '東京都'
 );

INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('01', '北海道');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('02', '青森県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('03', '岩手県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('04', '宮城県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('05', '秋田県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('06', '山形県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('07', '福島県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('08', '茨城県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('09', '栃木県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('10', '群馬県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('11', '埼玉県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('12', '千葉県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('13', '東京都');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('14', '神奈川県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('15', '新潟県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('16', '富山県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('17', '石川県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('18', '福井県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('19', '山梨県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('20', '長野県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('21', '岐阜県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('22', '静岡県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('23', '愛知県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('24', '三重県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('25', '滋賀県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('26', '京都府');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('27', '大阪府');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('28', '兵庫県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('29', '奈良県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('30', '和歌山県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('31', '鳥取県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('32', '島根県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('33', '岡山県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('34', '広島県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('35', '山口県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('36', '徳島県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('37', '香川県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('38', '愛媛県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('39', '高知県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('40', '福岡県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('41', '佐賀県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('42', '長崎県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('43', '熊本県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('44', '大分県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('45', '宮崎県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('46', '鹿児島県');
INSERT INTO DEPARTURE (DEP_CODE, DEP_NAME) VALUES ('47', '沖縄県');

INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('01', '北海道');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('02', '青森県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('03', '岩手県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('04', '宮城県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('05', '秋田県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('06', '山形県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('07', '福島県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('08', '茨城県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('09', '栃木県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('10', '群馬県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('11', '埼玉県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('12', '千葉県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('13', '東京都');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('14', '神奈川県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('15', '新潟県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('16', '富山県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('17', '石川県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('18', '福井県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('19', '山梨県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('20', '長野県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('21', '岐阜県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('22', '静岡県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('23', '愛知県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('24', '三重県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('25', '滋賀県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('26', '京都府');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('27', '大阪府');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('28', '兵庫県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('29', '奈良県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('30', '和歌山県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('31', '鳥取県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('32', '島根県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('33', '岡山県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('34', '広島県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('35', '山口県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('36', '徳島県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('37', '香川県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('38', '愛媛県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('39', '高知県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('40', '福岡県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('41', '佐賀県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('42', '長崎県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('43', '熊本県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('44', '大分県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('45', '宮崎県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('46', '鹿児島県');
INSERT INTO ARRIVAL (ARR_CODE, ARR_NAME) VALUES ('47', '沖縄県');

INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES ('0001', 'TERASOLUNAホテル第一荘', '018-123-4567');
INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES ('0002', 'TERASOLUNAホテル第二荘', '019-123-4567');
INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES ('0003', 'TERASOLUNAホテル第三荘', '020-123-4567');
INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES ('0004', 'TERASOLUNAホテル第四荘', '021-123-4567');
INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES ('0005', 'TERASOLUNAホテル第五荘', '022-123-4567');

INSERT INTO AGE (AGE_CODE, AGE_NAME, AGE_RATE) VALUES ('0', '大人', '100');
INSERT INTO AGE (AGE_CODE, AGE_NAME, AGE_RATE) VALUES ('1', '小人', '50');

INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000001', 'データ太郎', 'データタロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000002', 'データ次郎', 'データジロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000003', 'データ三郎', 'データサブロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000004', 'データ四郎', 'データシロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000005', 'データ五郎', 'データゴロウ', 'password');

COMMIT;
